addr: 127.0.0.1:9000           # HTTP绑定端口
wx:
  appId: wxe2054a88a0c095da
  appSecret: a6b04ca7e3c3aa20319d2685aa5add32
  oriId: gh_1fa4f0f5d6a9
  token: cmis110
  encodedAESKey: imZK0qotfx4eCJe61GSiVzA3ikdhZs5RHckmyi6GilW
